sudo: required
language: go
services:
  - docker

get_deps:
  - go get github.com/go-telegram-bot-api/telegram-bot-api

after_success:
  - docker build -t realsidsun/wallpaper-bot .
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push realsidsun/wallpaper-bot